// SPDX-License-Identifier: MIT
pragma solidity 0.8.27;

import {Test} from "forge-std/Test.sol";
import {HonkVerifier} from "../../src/verifier/IncomeVerifier.sol";

/// @title RealProofTest
/// @notice Runs the deployed verifier against a proof generated by the worker
///         from live Sepolia payroll events, rather than a mock.
/// @dev The fixture is written by `worker/src/prove.ts`. Regenerate it with
///      `npm run prove` in worker/ if the circuit changes.
contract RealProofTest is Test {
    HonkVerifier internal verifier;

    bytes internal proof;
    bytes32[] internal publicInputs;
    bytes32[] internal commitments;
    address internal subject;
    uint256 internal band;

    uint256 internal constant PERIODS = 3;

    function setUp() public {
        verifier = new HonkVerifier();

        string memory json = vm.readFile("./test/fixtures/income-proof.json");
        proof = vm.parseJsonBytes(json, ".proof");
        publicInputs = vm.parseJsonBytes32Array(json, ".publicInputs");
        commitments = vm.parseJsonBytes32Array(json, ".commitments");
        subject = vm.parseJsonAddress(json, ".subject");
        band = vm.parseJsonUint(json, ".band");
    }

    function test_realProofVerifies() public view {
        assertTrue(verifier.verify(proof, publicInputs), "real proof did not verify");
    }

    /// @dev 24 declared inputs less the 16 pairing-point slots carried in the
    ///      proof. CredentialRegistry.PUBLIC_INPUTS must equal this.
    function test_publicInputCountIsEight() public view {
        assertEq(publicInputs.length, 8);
        assertTrue(verifier.verify(proof, publicInputs));
    }

    function test_publicInputsCarryTheSubjectAndBand() public view {
        assertEq(address(uint160(uint256(publicInputs[0]))), subject);
        assertEq(uint256(publicInputs[1]), band);
    }

    /// @dev The limb split is what binds the proof to the attested commitment.
    ///      If it disagrees, SAME-COMMITMENT is unenforceable in both directions.
    function test_limbsReassembleToTheAnchoredCommitments() public view {
        for (uint256 i; i < PERIODS; ++i) {
            uint256 hi = uint256(publicInputs[2 + i * 2]);
            uint256 lo = uint256(publicInputs[3 + i * 2]);
            assertEq(bytes32((hi << 128) | lo), commitments[i], "limb reassembly mismatch");
            assertLe(hi, type(uint128).max);
            assertLe(lo, type(uint128).max);
        }
    }

    function test_tamperedBandIsRejected() public view {
        bytes32[] memory tampered = publicInputs;
        tampered[1] = bytes32(band + 1);
        assertFalse(_verifies(proof, tampered), "a different band still verified");
    }

    function test_tamperedSubjectIsRejected() public view {
        bytes32[] memory tampered = publicInputs;
        tampered[0] = bytes32(uint256(uint160(address(0xBEEF))));
        assertFalse(_verifies(proof, tampered), "a substituted subject still verified");
    }

    function test_tamperedCommitmentIsRejected() public view {
        bytes32[] memory tampered = publicInputs;
        tampered[2] = bytes32(uint256(tampered[2]) ^ 1);
        assertFalse(_verifies(proof, tampered), "a mutated commitment still verified");
    }

    function test_tamperedProofIsRejected() public view {
        bytes memory mutated = proof;
        mutated[mutated.length - 1] = bytes1(uint8(mutated[mutated.length - 1]) ^ 0x01);
        assertFalse(_verifies(mutated, publicInputs), "a mutated proof still verified");
    }

    /// @dev The generated verifier rejects by reverting (SumcheckFailed and
    ///      friends), not by returning false, so CredentialRegistry's
    ///      InvalidProof is reached only for the rare non-reverting rejection.
    ///      Both count as a rejection; returning true would not.
    function _verifies(bytes memory p, bytes32[] memory inputs) internal view returns (bool) {
        try verifier.verify(p, inputs) returns (bool ok) {
            return ok;
        } catch {
            return false;
        }
    }

    function test_wrongPublicInputCountReverts() public {
        bytes32[] memory short_ = new bytes32[](publicInputs.length - 1);
        for (uint256 i; i < short_.length; ++i) short_[i] = publicInputs[i];

        vm.expectRevert();
        verifier.verify(proof, short_);
    }
}
