// SPDX-License-Identifier: MIT
pragma solidity 0.8.27;

import {Test} from "forge-std/Test.sol";
import {HonkVerifier} from "../../src/verifier/IncomeVerifier.sol";

/// @title WasmProofTest
/// @notice Proves that a proof generated by bb.js in WebAssembly is accepted by
///         the same verifier as one from the native CLI.
/// @dev This is what makes in-browser proving safe to build on: the user's
///      machine produces the proof, so the amounts never leave it, and the
///      result still verifies on Creditcoin.
contract WasmProofTest is Test {
    HonkVerifier internal verifier;
    bytes internal proof;
    bytes32[] internal publicInputs;

    function setUp() public {
        verifier = new HonkVerifier();
        string memory json = vm.readFile("./test/fixtures/wasm-proof.json");
        proof = vm.parseJsonBytes(json, ".proof");
        publicInputs = vm.parseJsonBytes32Array(json, ".publicInputs");
    }

    function test_browserGeneratedProofVerifies() public view {
        assertEq(publicInputs.length, 8);
        assertTrue(verifier.verify(proof, publicInputs), "bb.js proof rejected by the verifier");
    }

    function test_carriesTheExpectedSubjectAndBand() public view {
        assertEq(
            address(uint160(uint256(publicInputs[0]))),
            0xBb605cf7604ef843e9Df15559257a73989DAe75A
        );
        assertEq(uint256(publicInputs[1]), 6, "band 6, $6,000-$10,000");
    }

    /// @dev The commitments Semuni anchored on Sepolia, reassembled from the
    ///      limbs the WASM prover produced.
    function test_limbsMatchTheAnchoredCommitments() public view {
        bytes32[3] memory expected = [
            bytes32(0x4324ad13f3fb1babcce363dfa125d40841ae21c665488213a7b4f34f1f6b255d),
            bytes32(0x7928367c26fea7a964cb58e43e822aad97162c4be227072cd56ad23aaa61670f),
            bytes32(0xe8bd1d0502da34112ea376503b75173b9b9fd2958534de181f7e5454ed518783)
        ];

        for (uint256 i; i < 3; ++i) {
            uint256 hi = uint256(publicInputs[2 + i * 2]);
            uint256 lo = uint256(publicInputs[3 + i * 2]);
            assertEq(bytes32((hi << 128) | lo), expected[i]);
        }
    }

    function test_tamperedBandIsRejected() public view {
        bytes32[] memory tampered = publicInputs;
        tampered[1] = bytes32(uint256(7));
        try verifier.verify(proof, tampered) returns (bool ok) {
            assertFalse(ok);
        } catch {}
    }
}
